title: Welcome to What A Simple Dash!
defaultColumns: 4
theme:
  mainBackground: '#111828'
  titleBackground: ''
  text: '#ffffff'
  serviceBackground: '#1f2937'
  serviceBackgroundHover: '#374151'
backgrounds:
  active: 1756499126393.jpeg
  history:
    - 1756337247995.jpeg
    - 1756339272601.jpeg
    - 1756499126393.jpeg
    - 1757448221924.jpeg
    - 1757448235930.jpeg
widgets:
  columns: 1
  items:
    - name: Clock
      type: clock
groups:
  - name: Getting Started
    services:
      - name: Edit This File!
        subtitle: Edit config/services.yml to start
        url: https://github.com/leraptor65/whatasimpledash
        icon: FaWrench
        backgroundColor: rgba(2,65,4,.5)
        textColor: rgba(255,255,255,1)
      - name: My GitHub
        subtitle: Visit the project repo
        url: https://github.com/leraptor65/whatasimpledash
        icon: FaGithub
      - name: Test 1
        align: right
        layout: horizontal-reverse
      - name: Test 2
        align: center
      - name: Test 3
        align: left
        layout: vertical
      - name: New Service
    align: left
    layout: horizontal
  - name: Group 2
    services:
      - name: Test 4
  - name: Group 3
    columns: 1
    services:
      - name: Test 5
        subtitle: This is a test service card
services:
  - name: New Item
settings:
  showTitleBackgrounds: true
  backgroundBlur: 4
  localIp: 192.168.68.180
